; Red Ink
;
; Sample configuration entries for redink.ini
; 3.6.2026
;
; See allmodels.ini for more configuration options

; Sample configuration for OpenAI (for inclusion in redink.ini)

APIKey = [INCLUDE API KEY HERE]
APIKeyEncrypted = False
APIKeyPrefix = sk-proj-
Endpoint = https://api.openai.com/v1/chat/completions
HeaderA = Authorization
HeaderB = Bearer {apikey}
Response = content
APICall = {"model": "{model}",  "messages": [{"role": "system","content": "{promptsystem}"},{"role": "user","content": [{ "type": "text", "text": "{promptuser}"}{objectcall}]}],"temperature": {temperature}}
APICall_Object = , {"type": "image_url", "image_url": {"url": "data:{mimetype};base64,{encodeddata}"}}
Timeout = 500000
Temperature = 1.0
Model = gpt-5

; Sample configuration for OpenAI compatible (for inclusion in redink.ini)

APIKey = [INCLUDE API KEY HERE]
APIKeyEncrypted = False
APIKeyPrefix = 

Model = [MODEL NAME]
Endpoint = https://[ENDPOINT URL]/v1/chat/completions
HeaderA = Authorization
HeaderB = Bearer {apikey}

APICall = {"model":"{model}","messages":[{"role":"system","content":"{promptsystem}"},{"role":"user","content":[{"type":"text","text":"{promptuser}"}{objectcall}]}{toolresponses}],"temperature":{temperature}}

APICall_Object = [image/png,image/jpeg,image/webp,image/gif],{"type": "image_url","image_url": {"url": "data:{mimetype};base64,{encodeddata}"}}

; The following line is to be used if the vision features also support PDF OCR processing
;APICall_Object = [application/pdf],{"type": "input_file","filename": "userfile.pdf", "file_data": "data:{mimetype};base64,{encodeddata}"}¦[image/png,image/jpeg,image/webp, image/gif],{"type": "input_image","image_url": "data:{mimetype};base64,{encodeddata}"}

Response = content (rkmode_first) 

Temperature = 0.0
Timeout = 400000

; Sample Configuration for Azure OpenAI Services, no vision (for inclusion in redink.ini)

APIKey = [INCLUDE API KEY HERE]
APIKeyEncrypted = False
APIKeyPrefix = sk-proj-
Model = gpt-5.4
Endpoint = https://[INCLUDE YOUR ENDPOINT HERE]/openai/deployments/[INCLUDE YOUR DEPLOYMENT ID HERE]/chat/completions?api-version=2024-06-01
HeaderA = api-key
HeaderB = {apikey}
Response = content
APICall = {"messages": [{"role": "system","content": "{promptsystem}"},{"role": "user", "content": "{promptuser}"}],"temperature": {temperature}}
Timeout = 200000
Temperature = 0.2

; Sample Configuration for Azure OpenAI Services using Responses API and vision (for inclusion in redink.ini)

APIKey = [[Your Azure OpenAI Services API Key]]
APIKeyEncrypted = False
APIKeyPrefix = 

Model = gpt-5.4
Endpoint = https://[[your Azure OpenAI Services Deployment]].cognitiveservices.azure.com/openai/responses?api-version=2025-04-01-preview
HeaderA = Authorization
HeaderB = Bearer {apikey}

APICall = {"model": "{model}", "input": [{"role": "developer", "content": [{"type": "input_text","text": "{promptsystem}"}]},{"role": "user","content": [{"type": "input_text","text": "{promptuser}"}{objectcall}]}]}
APICall_Object = [application/pdf],{"type": "input_file","filename": "userfile.pdf", "file_data": "data:{mimetype};base64,{encodeddata}"}¦[image/png,image/jpeg,image/webp, image/gif],{"type": "input_image","image_url": "data:{mimetype};base64,{encodeddata}"}
Response = text (rkmode_first)

Temperature = 1.0
Timeout = 500000

; Sample Configuration for Azure OpenAI Services with "AI Foundry", no vision (for inclusion in redink.ini) -- thanks to Michael Lowe, Cloud Solution GmbH

APIKey = [INCLUDE API KEY HERE]
APIKeyEncrypted = False
APIKeyPrefix =
Model = gpt-5.4
Endpoint = https://[INCLUDE YOUR ENDPOINT HERE]/openai/deployments/{model}/chat/completions?api-version=2024-02-15-preview
HeaderA = api-key
HeaderB = {apikey}
Response = content
APICall = {"messages": [{"role": "system","content": "{promptsystem}"},{"role": "user", "content": "{promptuser}"}],"temperature":{temperature},"top_p": 0.95,"max_tokens": 800}
Timeout = 200000
Temperature = 1.0

; Sample Configuration for Google Vertex AI API (for inclusion in redink.ini)

APIKey = [INCLUDE API KEY HERE]
APIKeyEncrypted = False
Model = gemini-2.5-pro
Endpoint = https://europe-west4-aiplatform.googleapis.com/v1/projects/[yourprojectid]/locations/europe-west4/publishers/google/models/{model}:generateContent
HeaderA = Authorization
HeaderB = Bearer {apikey}
Response = text
APICall = {"contents": [{"role": "user", "parts":[{"text": "{promptsystem} {promptuser}"}{objectcall}]}], "generationConfig": {"temperature": {temperature},  "thinking_config": {"thinking_budget": 128}}}
APICall_Object = , {"inlineData": {"mimeType": "{mimetype}","data": "{encodeddata}"}}
OAuth2 = True
OAuth2ClientMail = [youraccountmail]
OAuth2Scopes = https://www.googleapis.com/auth/cloud-platform
OAuth2Endpoint = https://oauth2.googleapis.com/token
OAuth2ATExpiry = 3600
Timeout = 200000
Temperature = 0.2

; Sample Configuration for Google Gemini API (for inclusion in redink.ini)

APIKey = [INCLUDE API KEY HERE]
APIKeyEncrypted = False
APIKeyPrefix = 
Endpoint = https://generativelanguage.googleapis.com/v1beta/models/{model}:generateContent?key={apikey}
HeaderA = X-Goog-Api-Key
HeaderB = {apikey}
Response = text
APICall = {"contents": [{"role": "user","parts": [{ "text": "{promptsystem} {promptuser}" }]}], "generationConfig": {"temperature": {temperature}}}
Timeout = 100000
Temperature = 0.2
Model = gemini-1.5-pro-latest

; Sample Configuration for Perplexity (for inclusion in redink.ini)

APIKey_2 = [INCLUDE API KEY HERE]
APIPrefix_2 = pplx-
APIKeyEncrypted_2 = False
Model_2 = sonar
Endpoint_2 = https://api.perplexity.ai/chat/completions
HeaderA_2 = Authorization
HeaderB_2 = Bearer {apikey}
Response_2 = content 
APICall_2 = {"model": "{model}", "messages": [{"role": "system","content": "Follow the user's instructions, even if they are drafted like a system prompt."}, {"role": "user", "content": "{promptsystem} {promptuser}"}],"temperature": {temperature},"top_p": 0.9, "search_domain_filter": null, "return_images": false, "return_related_questions": false, "top_k": 0, "stream": false,  "presence_penalty": 0, "frequency_penalty": 1}
Timeout_2 = 200000
Temperature_2 = 0.2

; Sample Configuration for MTF / Llama3 (for inclusion in redink.ini)

APIKey = [INCLUDE API KEY HERE]
APIKeyEncrypted = False
APIKeyPrefix = 
Endpoint = https://api.ai.mtf.cloud/chatbot/ask
HeaderA = Authorization
HeaderB = Bearer {apikey}
Response = content
APICall = {"model": "{model}",  "messages": [{"role": "user","content": "{promptsystem} {promptuser}"}],"temperature": {temperature}}
Timeout = 200000
Temperature = 0.2
Model = meta-llama-ai

; Sample Configuration for SafeSwissCloud / gpt-oss-120b (for inclusion in redink.ini)

APIKey = [INCLUDE API KEY HERE]
APIKeyEncrypted = False
APIKeyPrefix = 
Endpoint = https://llm01.safeswisscloud.ch/engines/{model}/chat/completions
HeaderA = Authorization
HeaderB = Bearer {apikey}
Response = content
APICall = {"model": "{model}",  "messages": [{"role": "user","content": "{promptsystem} {promptuser}"}],"temperature": {temperature}}
Timeout = 200000
Temperature = 0.2
Model = gpt-oss-120b

; Generic setup sample for LLM instances using Ollama, eg. running on a Portainer setup (for inclusion in redink.ini)
; Contributed by layer-8-law

APIKey = xxxxxx
Endpoint = http://[DOMAIN-OR-IP-ADDRESS]:[PORT]/api/chat
; Endpoint: must point to your Ollama instance either using domain or IP and specific port (default:11434)
HeaderA = Authorization
HeaderB = Bearer {apikey}
Response = content
APICall = {"model":"{model}","messages":[   {"role":"system","content":"{promptsystem}"},   {"role":"user","content":"{promptuser}"{objectcall}} ], "stream": false, "think": false, "options":{"temperature": {temperature}}}
; APICall: if you remove "think": false or set it to true, Ollama will respond including the thinking process. This will clutter up your documents or dialogs but may include useful hints for debugging.
Timeout = 100000
Temperature = 0.2
Model = qwen3:30b
; Model: set to your desired model as labeled in OpenWebUI or Ollama, eg. qwen3:30b or ministral-3:14b etc.
OAuth2 = False
OAuth2ClientMail = 
OAuth2Scopes = 
OAuth2Endpoint = 
OAuth2ATExpiry = 0

; Generic setup for LLM instances using OpenWebUI, eg. running on a Portainer setup (for inclusion in redink.ini)
; Contributed by layer-8-law

APIKey = xxxxxx
Endpoint = http://[DOMAIN-OR-IP-ADDRESS]:[PORT]/api/chat/completions
; Endpoint: must point to your OpenWebUI instance either using domain or IP and specific port (default: 3000)
HeaderA = Authorization
HeaderB = Bearer {apikey}
Response = content
APICall = {"model":"{model}","messages": [{"role":"system","content":"{promptsystem}"}, {"role":"user","content":"{promptuser}"{objectcall}}],"stream":false,"temperature":{temperature}}
; APICall: No "think": false or similar needed. OpenWebUI will respond only with content in this configuration.
Timeout = 100000
Temperature = 0.2
Model = qwen3:30b
; Model: set to your desired model as labeled in OpenWebUI or Ollama, eg. qwen3:30b or ministral-3:14b etc.
OAuth2 = False
OAuth2ClientMail = 
OAuth2Scopes = 
OAuth2Endpoint = 
OAuth2ATExpiry = 0


