; Schema:
; [ProviderName]
; Note = Optional text to show under the fields
; Field1 = DisplayName|VarName|VarType|ValidationRule|DefaultValue
; Field2 = ...
; ValidationRule supports: NotEmpty, E-Mail, Hyperlink, >0, 0.0-2.0 (same as built-in)
; 04 May 2026

[OpenAI]
Note=Note: When generating the API key with OpenAI, make sure you have added a valid payment method (e.g., credit card), even if you use ChatGPT for free or with an already paid subscription. You still need the payment method and a budget to pay for the actual consumption (costs are in our experience low).
Field1=API Key:|INI_APIKey|String|NotEmpty|[[Your OpenAI API Key]]
Field2=Timeout (ms):|INI_Timeout|Integer|>0|300000
Field3=Model:|INI_Model|String|NotEmpty|gpt-5.4
Field4=Endpoint:|INI_Endpoint|String|Hyperlink|https://api.openai.com/v1/responses
Field5=HeaderA:|INI_HeaderA|String||Authorization
Field6=HeaderB:|INI_HeaderB|String||Bearer {apikey}
Field7=APICall:|INI_APICall|String|NotEmpty|{"model":"{model}","input":[{"role":"developer","content":[{"type":"input_text","text":"{promptsystem}"}]},{"role":"user","content":[{"type":"input_text","text":"{promptuser}"}{objectcall}]}],"reasoning":{"effort":"low"}}
Field8=APICall_Object:|INI_APICall_Object|String||[application/pdf],{"type":"input_file","filename":"userfile.pdf","file_data":"data:{mimetype};base64,{encodeddata}"}¦[image/png,image/jpeg,image/webp, image/gif],{"type":"input_image","image_url":"data:{mimetype};base64,{encodeddata}"}
Field9=Response tag:|INI_Response|String|NotEmpty|text (rkmode_first)

[Microsoft Azure OpenAI Services]
Note=These may not be the latest possible settings available in your environment. Check your documentation to update this.
Field1=API Key:|INI_APIKey|String|NotEmpty|[[Your Azure OpenAI Services API Key]]
Field2=Timeout (ms):|INI_Timeout|Integer|>0|300000
Field3=Model:|INI_Model|String|NotEmpty|gpt-5.4
Field4=Endpoint:|INI_Endpoint|String|Hyperlink|https://[[Your Azure OpenAI Services Deployment]].cognitiveservices.azure.com/openai/responses?api-version=2025-04-01-preview
Field5=HeaderA:|INI_HeaderA|String||Authorization
Field6=HeaderB:|INI_HeaderB|String||Bearer {apikey}
Field7=APICall:|INI_APICall|String|NotEmpty|{"model": "{model}", "input": [{"role": "developer", "content": [{"type": "input_text","text": "{promptsystem}"}]},{"role": "user","content": [{"type": "input_text","text": "{promptuser}"}{objectcall}]}]}
Field8=APICall_Object:|INI_APICall_Object|String||[application/pdf],{"type": "input_file","filename": "userfile.pdf", "file_data": "data:{mimetype};base64,{encodeddata}"}¦[image/png,image/jpeg,image/webp, image/gif],{"type": "input_image","image_url": "data:{mimetype};base64,{encodeddata}"}
Field9=Response tag:|INI_Response|String|NotEmpty|text (rkmode_first)

[Google Gemini]
Field1=API Key:|INI_APIKey|String|NotEmpty|[[Your Google API Key]]
Field2=Temperature:|INI_Temperature|String|0.0-2.0|0.2
Field3=Timeout (ms):|INI_Timeout|Integer|>0|300000
Field4=Model:|INI_Model|String|NotEmpty|gemini-2.5-pro
Field5=Endpoint:|INI_Endpoint|String|Hyperlink|https://generativelanguage.googleapis.com/v1beta/models/{model}:generateContent?key={apikey}
Field6=HeaderA:|INI_HeaderA|String||X-Goog-Api-Key
Field7=HeaderB:|INI_HeaderB|String||{apikey}
Field8=APICall:|INI_APICall|String|NotEmpty|{"contents":[{"role":"user","parts":[{"text":"{promptsystem} {promptuser}"}]}],"generationConfig":{"temperature":{temperature}}}
Field9=Response tag:|INI_Response|String|NotEmpty|text

[Anthropic]
Field1=API Key:|INI_APIKey|String|NotEmpty|[[Your Anthropic API Key]]
Field2=Model:|INI_Model|String|NotEmpty|claude-sonnet-4-6
Field3=Endpoint:|INI_Endpoint|String|Hyperlink|https://api.anthropic.com/v1/messages
Field4=HeaderA:|INI_HeaderA|String||x-api-key¦anthropic-version
Field5=HeaderB:|INI_HeaderB|String||{apikey}¦2023-06-01
Field6=APICall:|INI_APICall|String|NotEmpty|{"model": "{model}","max_tokens": 64000, "messages": [{"role": "user", "content": "{promptsystem} {promptuser}"}]}
Field7=APICall_Object:|INI_APICall_Object|String||
Field8=Response tag:|INI_Response|String|NotEmpty|text (rkmode_first)
Field9=Temperature:|INI_Temperature|String|0.0-2.0|1.0
Field10=Timeout (ms):|INI_Timeout|Integer|>0|200000

[Google Vertex]
Note=Note: Requires OAuth2 service account to be configured via the GCP console. Private Key must be the raw key (not PEM).
Field1=Private Key (barebones, not PEM):|INI_APIKey|String|NotEmpty|[[Your Google private_key]]
Field2=Temperature:|INI_Temperature|String|2.0|0.2
Field3=Timeout (ms):|INI_Timeout|Integer|>0|300000
Field4=Model:|INI_Model|String|NotEmpty|gemini-2.5-pro
Field5=Endpoint:|INI_Endpoint|String|Hyperlink|https://europe-west4-aiplatform.googleapis.com/v1/projects/[[Your Google project_id]]/locations/europe-west4/publishers/google/models/{model}:generateContent
Field6=HeaderA:|INI_HeaderA|String||Authorization
Field7=HeaderB:|INI_HeaderB|String||Bearer {apikey}
Field8=APICall:|INI_APICall|String|NotEmpty|{"contents":[{"role":"user","parts":[{"text":"{promptsystem} {promptuser}"}{objectcall}]}],"generationConfig":{"temperature":{temperature},"thinking_config":{"thinking_budget":128}}}
Field9=APICall_Object:|INI_APICall_Object|String||, {"inlineData": {"mimeType": "{mimetype}","data": "{encodeddata}"}}
Field10=Response tag:|INI_Response|String|NotEmpty|text
Field11=OAuth2 'client_mail':|INI_OAuth2ClientMail|String|E-Mail|[[Your Google client_email]]
Field12=OAuth2 'scopes':|INI_OAuth2Scopes|String|NotEmpty|https://www.googleapis.com/auth/cloud-platform
Field13=OAuth2 Endpoint:|INI_OAuth2Endpoint|String|Hyperlink|https://oauth2.googleapis.com/token
Field14=OAuth2 Access Token Expiry (seconds):|INI_OAuth2ATExpiry|Integer|>0|3600

[MTF]
Field1=API Key:|INI_APIKey|String|NotEmpty|
Field2=Temperature:|INI_Temperature|String|2.0|0.2
Field3=Timeout (ms):|INI_Timeout|Integer|>0|200000
Field4=Model:|INI_Model|String|NotEmpty|openai-gpt-oss-20b
Field5=Endpoint:|INI_Endpoint|String|Hyperlink|https://api.ai.mtf.cloud/v1/chat/completions
Field6=HeaderA:|INI_HeaderA|String||Authorization
Field7=HeaderB:|INI_HeaderB|String||Bearer {apikey}
Field8=APICall:|INI_APICall|String|NotEmpty|{"model":"{model}","messages":[{"role":"system","content":"{promptsystem}"},{"role":"user","content":"{promptuser}"}],"temperature":{temperature}}
Field9=Response tag:|INI_Response|String|NotEmpty|content

[SafeSwissCloud]
Field1=API Key:|INI_APIKey|String|NotEmpty|
Field2=Temperature:|INI_Temperature|String|0.0-2.0|0.2
Field3=Timeout (ms):|INI_Timeout|Integer|>0|200000
Field4=Model:|INI_Model|String|NotEmpty|gpt-oss-120b
Field5=Endpoint:|INI_Endpoint|String|Hyperlink|https://llm01.safeswisscloud.ch/engines/{model}/chat/completions
Field6=HeaderA:|INI_HeaderA|String||Authorization
Field7=HeaderB:|INI_HeaderB|String||Bearer {apikey}
Field8=APICall:|INI_APICall|String|NotEmpty|{"model":"{model}","messages":[{"role":"system","content":"{promptsystem}"},{"role":"user","content":"{promptuser}"}],"temperature":{temperature}}
Field9=Response tag:|INI_Response|String|NotEmpty|content

[llama.cpp (local)]
Field1=API Key:|INI_APIKey|String|NotEmpty|dummy
Field2=Endpoint:|INI_Endpoint|String|Hyperlink|http://localhost:8080/v1/chat/completions
Field3=Response tag:|INI_Response|String|NotEmpty|content
Field4=APICall:|INI_APICall|String|NotEmpty|{"messages":[{"role":"system","content":"{promptsystem}"},{"role":"user","content":"{promptuser}"} ], "temperature": {temperature}}
Field5=Timeout (ms):|INI_Timeout|Integer|>0|200000
Field6=Temperature:|INI_Temperature|String|0.0-2.0|0.2
Field7=Model:|INI_Model|String|NotEmpty|AnyModel

[Ollama (local)]
Field1=API Key:|INI_APIKey|String|NotEmpty|dummy
Field2=Endpoint:|INI_Endpoint|String|Hyperlink|http://[[Your Domain Or IP Address]:[[Your Port]]/api/chat
Field3=HeaderA:|INI_HeaderA|String||Authorization
Field4=HeaderB:|INI_HeaderB|String||Bearer {apikey}
Field5=Response tag:|INI_Response|String|NotEmpty|content
Field6=APICall:|INI_APICall|String|NotEmpty|{"model":"{model}","messages":[   {"role":"system","content":"{promptsystem}"},   {"role":"user","content":"{promptuser}"{objectcall}} ], "stream": false, "think": false, "options":{"temperature": {temperature}}}
Field7=Timeout (ms):|INI_Timeout|Integer|>0|200000
Field8=Temperature:|INI_Temperature|String|0.0-2.0|0.2
Field9=Model:|INI_Model|String|NotEmpty|[[Your Model]]

[OpenWebUI (local)]
Field1=API Key:|INI_APIKey|String|NotEmpty|dummy
Field2=Endpoint:|INI_Endpoint|String|Hyperlink|http://[[Your Domain Or IP Address]:[[Your Port]]/api/chat/completions
Field3=HeaderA:|INI_HeaderA|String||Authorization
Field4=HeaderB:|INI_HeaderB|String||Bearer {apikey}
Field5=Response tag:|INI_Response|String|NotEmpty|content
Field6=APICall:|INI_APICall|String|NotEmpty|{"model":"{model}","messages": [{"role":"system","content":"{promptsystem}"}, {"role":"user","content":"{promptuser}"{objectcall}}],"stream":false,"temperature":{temperature}}
Field7=Timeout (ms):|INI_Timeout|Integer|>0|200000
Field8=Temperature:|INI_Temperature|String|0.0-2.0|0.2
Field9=Model:|INI_Model|String|NotEmpty|[[Your Model]]