'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property LastPrompt() As String
            Get
                Return CType(Me("LastPrompt"),String)
            End Get
            Set
                Me("LastPrompt") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property LastChatHistory() As String
            Get
                Return CType(Me("LastChatHistory"),String)
            End Get
            Set
                Me("LastChatHistory") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0, 0")>  _
        Public Property FormLocation() As Global.System.Drawing.Point
            Get
                Return CType(Me("FormLocation"),Global.System.Drawing.Point)
            End Get
            Set
                Me("FormLocation") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0, 0")>  _
        Public Property FormSize() As Global.System.Drawing.Size
            Get
                Return CType(Me("FormSize"),Global.System.Drawing.Size)
            End Get
            Set
                Me("FormSize") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DoCommands() As Boolean
            Get
                Return CType(Me("DoCommands"),Boolean)
            End Get
            Set
                Me("DoCommands") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property IncludeDocument() As Boolean
            Get
                Return CType(Me("IncludeDocument"),Boolean)
            End Get
            Set
                Me("IncludeDocument") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property IncludeSelection() As Boolean
            Get
                Return CType(Me("IncludeSelection"),Boolean)
            End Get
            Set
                Me("IncludeSelection") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property NotAlwaysOnTop() As Boolean
            Get
                Return CType(Me("NotAlwaysOnTop"),Boolean)
            End Get
            Set
                Me("NotAlwaysOnTop") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CSV_Prompt() As String
            Get
                Return CType(Me("CSV_Prompt"),String)
            End Get
            Set
                Me("CSV_Prompt") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute(";")>  _
        Public Property CSV_Separator() As String
            Get
                Return CType(Me("CSV_Separator"),String)
            End Get
            Set
                Me("CSV_Separator") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CSV_Columns() As String
            Get
                Return CType(Me("CSV_Columns"),String)
            End Get
            Set
                Me("CSV_Columns") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("50")>  _
        Public Property CSV_ChunkSize() As Integer
            Get
                Return CType(Me("CSV_ChunkSize"),Integer)
            End Get
            Set
                Me("CSV_ChunkSize") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property CSV_StartSelection() As Integer
            Get
                Return CType(Me("CSV_StartSelection"),Integer)
            End Get
            Set
                Me("CSV_StartSelection") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property CSV_EndSelection() As Integer
            Get
                Return CType(Me("CSV_EndSelection"),Integer)
            End Get
            Set
                Me("CSV_EndSelection") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property CSV_ResultStartLine() As Integer
            Get
                Return CType(Me("CSV_ResultStartLine"),Integer)
            End Get
            Set
                Me("CSV_ResultStartLine") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property CSV_ResultStartColumn() As Integer
            Get
                Return CType(Me("CSV_ResultStartColumn"),Integer)
            End Get
            Set
                Me("CSV_ResultStartColumn") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
        Public Property CSV_Attemps() As Integer
            Get
                Return CType(Me("CSV_Attemps"),Integer)
            End Get
            Set
                Me("CSV_Attemps") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property CSV_UseSecondModel() As Boolean
            Get
                Return CType(Me("CSV_UseSecondModel"),Boolean)
            End Get
            Set
                Me("CSV_UseSecondModel") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Extractor_ManualInstruction() As String
            Get
                Return CType(Me("Extractor_ManualInstruction"),String)
            End Get
            Set
                Me("Extractor_ManualInstruction") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Extractor_DateColumns() As String
            Get
                Return CType(Me("Extractor_DateColumns"),String)
            End Get
            Set
                Me("Extractor_DateColumns") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Extractor_SortColumn() As String
            Get
                Return CType(Me("Extractor_SortColumn"),String)
            End Get
            Set
                Me("Extractor_SortColumn") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Extractor_SortDirection() As String
            Get
                Return CType(Me("Extractor_SortDirection"),String)
            End Get
            Set
                Me("Extractor_SortDirection") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Extractor_DoOcr() As Boolean
            Get
                Return CType(Me("Extractor_DoOcr"),Boolean)
            End Get
            Set
                Me("Extractor_DoOcr") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Extractor_DateClampFrom() As String
            Get
                Return CType(Me("Extractor_DateClampFrom"),String)
            End Get
            Set
                Me("Extractor_DateClampFrom") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Extractor_DateClampTo() As String
            Get
                Return CType(Me("Extractor_DateClampTo"),String)
            End Get
            Set
                Me("Extractor_DateClampTo") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Extractor_OutputLanguage() As String
            Get
                Return CType(Me("Extractor_OutputLanguage"),String)
            End Get
            Set
                Me("Extractor_OutputLanguage") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Extractor_DateOutputFormat() As String
            Get
                Return CType(Me("Extractor_DateOutputFormat"),String)
            End Get
            Set
                Me("Extractor_DateOutputFormat") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Extractor_ManualSchema() As String
            Get
                Return CType(Me("Extractor_ManualSchema"),String)
            End Get
            Set
                Me("Extractor_ManualSchema") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Rename_ManualInstruction() As String
            Get
                Return CType(Me("Rename_ManualInstruction"),String)
            End Get
            Set
                Me("Rename_ManualInstruction") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Rename_OutputLanguage() As String
            Get
                Return CType(Me("Rename_OutputLanguage"),String)
            End Get
            Set
                Me("Rename_OutputLanguage") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Extractor_MergeEnable() As Boolean
            Get
                Return CType(Me("Extractor_MergeEnable"),Boolean)
            End Get
            Set
                Me("Extractor_MergeEnable") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Extractor_MergeDateColumn() As String
            Get
                Return CType(Me("Extractor_MergeDateColumn"),String)
            End Get
            Set
                Me("Extractor_MergeDateColumn") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Extractor_MergeInstruction() As String
            Get
                Return CType(Me("Extractor_MergeInstruction"),String)
            End Get
            Set
                Me("Extractor_MergeInstruction") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ChatInkyMemory() As Boolean
            Get
                Return CType(Me("ChatInkyMemory"),Boolean)
            End Get
            Set
                Me("ChatInkyMemory") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property DIR_Prompt() As String
            Get
                Return CType(Me("DIR_Prompt"),String)
            End Get
            Set
                Me("DIR_Prompt") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10")>  _
        Public Property DIR_ChunkSize() As Integer
            Get
                Return CType(Me("DIR_ChunkSize"),Integer)
            End Get
            Set
                Me("DIR_ChunkSize") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("4000")>  _
        Public Property DIR_MaxContentChars() As Integer
            Get
                Return CType(Me("DIR_MaxContentChars"),Integer)
            End Get
            Set
                Me("DIR_MaxContentChars") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property DIR_ResultStartLine() As Integer
            Get
                Return CType(Me("DIR_ResultStartLine"),Integer)
            End Get
            Set
                Me("DIR_ResultStartLine") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property DIR_ResultStartColumn() As Integer
            Get
                Return CType(Me("DIR_ResultStartColumn"),Integer)
            End Get
            Set
                Me("DIR_ResultStartColumn") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
        Public Property DIR_Attempts() As Integer
            Get
                Return CType(Me("DIR_Attempts"),Integer)
            End Get
            Set
                Me("DIR_Attempts") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DIR_UseSecondModel() As Boolean
            Get
                Return CType(Me("DIR_UseSecondModel"),Boolean)
            End Get
            Set
                Me("DIR_UseSecondModel") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property DIR_StartFile() As Integer
            Get
                Return CType(Me("DIR_StartFile"),Integer)
            End Get
            Set
                Me("DIR_StartFile") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property DIR_FileCount() As Integer
            Get
                Return CType(Me("DIR_FileCount"),Integer)
            End Get
            Set
                Me("DIR_FileCount") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ChatContextPath() As String
            Get
                Return CType(Me("ChatContextPath"),String)
            End Get
            Set
                Me("ChatContextPath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ChatPersistContext() As Boolean
            Get
                Return CType(Me("ChatPersistContext"),Boolean)
            End Get
            Set
                Me("ChatPersistContext") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.Red_Ink_for_Excel.My.MySettings
            Get
                Return Global.Red_Ink_for_Excel.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
