'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property LastChatHistory() As String
            Get
                Return CType(Me("LastChatHistory"),String)
            End Get
            Set
                Me("LastChatHistory") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0, 0")>  _
        Public Property FormLocation() As Global.System.Drawing.Point
            Get
                Return CType(Me("FormLocation"),Global.System.Drawing.Point)
            End Get
            Set
                Me("FormLocation") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0, 0")>  _
        Public Property FormSize() As Global.System.Drawing.Size
            Get
                Return CType(Me("FormSize"),Global.System.Drawing.Size)
            End Get
            Set
                Me("FormSize") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property DoCommands() As Boolean
            Get
                Return CType(Me("DoCommands"),Boolean)
            End Get
            Set
                Me("DoCommands") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property IncludeDocument() As Boolean
            Get
                Return CType(Me("IncludeDocument"),Boolean)
            End Get
            Set
                Me("IncludeDocument") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property IncludeSelection() As Boolean
            Get
                Return CType(Me("IncludeSelection"),Boolean)
            End Get
            Set
                Me("IncludeSelection") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property NotAlwaysOnTop() As Boolean
            Get
                Return CType(Me("NotAlwaysOnTop"),Boolean)
            End Get
            Set
                Me("NotAlwaysOnTop") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property LastPrompt() As String
            Get
                Return CType(Me("LastPrompt"),String)
            End Get
            Set
                Me("LastPrompt") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property LastSpeechModel() As String
            Get
                Return CType(Me("LastSpeechModel"),String)
            End Get
            Set
                Me("LastSpeechModel") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property LastAudioSource() As String
            Get
                Return CType(Me("LastAudioSource"),String)
            End Get
            Set
                Me("LastAudioSource") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property LastSpeakerEnabled() As Boolean
            Get
                Return CType(Me("LastSpeakerEnabled"),Boolean)
            End Get
            Set
                Me("LastSpeakerEnabled") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property LastSpeakerDistance() As Double
            Get
                Return CType(Me("LastSpeakerDistance"),Double)
            End Get
            Set
                Me("LastSpeakerDistance") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property LastVoice() As String
            Get
                Return CType(Me("LastVoice"),String)
            End Get
            Set
                Me("LastVoice") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property TTS1languagecode() As String
            Get
                Return CType(Me("TTS1languagecode"),String)
            End Get
            Set
                Me("TTS1languagecode") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property TTS1voiceA() As String
            Get
                Return CType(Me("TTS1voiceA"),String)
            End Get
            Set
                Me("TTS1voiceA") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property TTS1voiceB() As String
            Get
                Return CType(Me("TTS1voiceB"),String)
            End Get
            Set
                Me("TTS1voiceB") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property TTS2languagecode() As String
            Get
                Return CType(Me("TTS2languagecode"),String)
            End Get
            Set
                Me("TTS2languagecode") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property TTS2voiceA() As String
            Get
                Return CType(Me("TTS2voiceA"),String)
            End Get
            Set
                Me("TTS2voiceA") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property TTS2voiceB() As String
            Get
                Return CType(Me("TTS2voiceB"),String)
            End Get
            Set
                Me("TTS2voiceB") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property TTSSampleText() As String
            Get
                Return CType(Me("TTSSampleText"),String)
            End Get
            Set
                Me("TTSSampleText") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property TTSOutputPath() As String
            Get
                Return CType(Me("TTSOutputPath"),String)
            End Get
            Set
                Me("TTSOutputPath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property TTSLastRdoOneVoice() As String
            Get
                Return CType(Me("TTSLastRdoOneVoice"),String)
            End Get
            Set
                Me("TTSLastRdoOneVoice") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property TTSLastRdoTwoVoices() As String
            Get
                Return CType(Me("TTSLastRdoTwoVoices"),String)
            End Get
            Set
                Me("TTSLastRdoTwoVoices") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property NoSSML() As Boolean
            Get
                Return CType(Me("NoSSML"),Boolean)
            End Get
            Set
                Me("NoSSML") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property Pitch() As Double
            Get
                Return CType(Me("Pitch"),Double)
            End Get
            Set
                Me("Pitch") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property Speakingrate() As Double
            Get
                Return CType(Me("Speakingrate"),Double)
            End Get
            Set
                Me("Speakingrate") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Lisa")>  _
        Public Property Hostname() As String
            Get
                Return CType(Me("Hostname"),String)
            End Get
            Set
                Me("Hostname") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Peter")>  _
        Public Property Guestname() As String
            Get
                Return CType(Me("Guestname"),String)
            End Get
            Set
                Me("Guestname") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("general audience")>  _
        Public Property TargetAudience() As String
            Get
                Return CType(Me("TargetAudience"),String)
            End Get
            Set
                Me("TargetAudience") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property DialogueContext() As String
            Get
                Return CType(Me("DialogueContext"),String)
            End Get
            Set
                Me("DialogueContext") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1000 words")>  _
        Public Property Duration() As String
            Get
                Return CType(Me("Duration"),String)
            End Get
            Set
                Me("Duration") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("English")>  _
        Public Property Language() As String
            Get
                Return CType(Me("Language"),String)
            End Get
            Set
                Me("Language") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ExtraInstructions() As String
            Get
                Return CType(Me("ExtraInstructions"),String)
            End Get
            Set
                Me("ExtraInstructions") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property LastContextSearch() As String
            Get
                Return CType(Me("LastContextSearch"),String)
            End Get
            Set
                Me("LastContextSearch") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CleanTextPrompt() As String
            Get
                Return CType(Me("CleanTextPrompt"),String)
            End Get
            Set
                Me("CleanTextPrompt") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property AudioOutputDevice() As String
            Get
                Return CType(Me("AudioOutputDevice"),String)
            End Get
            Set
                Me("AudioOutputDevice") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property TTSProvider() As String
            Get
                Return CType(Me("TTSProvider"),String)
            End Get
            Set
                Me("TTSProvider") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property LastFreestyleModelConfig() As Global.SharedLibrary.SharedLibrary.ModelConfig
            Get
                Return CType(Me("LastFreestyleModelConfig"),Global.SharedLibrary.SharedLibrary.ModelConfig)
            End Get
            Set
                Me("LastFreestyleModelConfig") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property LastFreestylePrompt() As String
            Get
                Return CType(Me("LastFreestylePrompt"),String)
            End Get
            Set
                Me("LastFreestylePrompt") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property LastFreestyleWasAM() As Boolean
            Get
                Return CType(Me("LastFreestyleWasAM"),Boolean)
            End Get
            Set
                Me("LastFreestyleWasAM") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ConvertMarkdownInChat() As Boolean
            Get
                Return CType(Me("ConvertMarkdownInChat"),Boolean)
            End Get
            Set
                Me("ConvertMarkdownInChat") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property LastChatHistoryHtml() As String
            Get
                Return CType(Me("LastChatHistoryHtml"),String)
            End Get
            Set
                Me("LastChatHistoryHtml") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Redaction_ManualInstruction() As String
            Get
                Return CType(Me("Redaction_ManualInstruction"),String)
            End Get
            Set
                Me("Redaction_ManualInstruction") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Redaction_OutputSubdir() As String
            Get
                Return CType(Me("Redaction_OutputSubdir"),String)
            End Get
            Set
                Me("Redaction_OutputSubdir") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Redaction_OutputExtension() As String
            Get
                Return CType(Me("Redaction_OutputExtension"),String)
            End Get
            Set
                Me("Redaction_OutputExtension") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Flatten_OutputSubdir() As String
            Get
                Return CType(Me("Flatten_OutputSubdir"),String)
            End Get
            Set
                Me("Flatten_OutputSubdir") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Flatten_OutputExtension() As String
            Get
                Return CType(Me("Flatten_OutputExtension"),String)
            End Get
            Set
                Me("Flatten_OutputExtension") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0, 0")>  _
        Public Property DiscussFormLocation() As Global.System.Drawing.Point
            Get
                Return CType(Me("DiscussFormLocation"),Global.System.Drawing.Point)
            End Get
            Set
                Me("DiscussFormLocation") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0, 0")>  _
        Public Property DiscussFormSize() As Global.System.Drawing.Size
            Get
                Return CType(Me("DiscussFormSize"),Global.System.Drawing.Size)
            End Get
            Set
                Me("DiscussFormSize") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DiscussIncludeActiveDoc() As Boolean
            Get
                Return CType(Me("DiscussIncludeActiveDoc"),Boolean)
            End Get
            Set
                Me("DiscussIncludeActiveDoc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property DiscussSelectedPersona() As String
            Get
                Return CType(Me("DiscussSelectedPersona"),String)
            End Get
            Set
                Me("DiscussSelectedPersona") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property DiscussKnowledgePath() As String
            Get
                Return CType(Me("DiscussKnowledgePath"),String)
            End Get
            Set
                Me("DiscussKnowledgePath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property DiscussLastChat() As String
            Get
                Return CType(Me("DiscussLastChat"),String)
            End Get
            Set
                Me("DiscussLastChat") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property DiscussLastChatHtml() As String
            Get
                Return CType(Me("DiscussLastChatHtml"),String)
            End Get
            Set
                Me("DiscussLastChatHtml") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DocStyle_TrackChanges() As Boolean
            Get
                Return CType(Me("DocStyle_TrackChanges"),Boolean)
            End Get
            Set
                Me("DocStyle_TrackChanges") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property DocStyle_ApplyStyleDefinitions() As Boolean
            Get
                Return CType(Me("DocStyle_ApplyStyleDefinitions"),Boolean)
            End Get
            Set
                Me("DocStyle_ApplyStyleDefinitions") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DocStyle_PreviewMode() As Boolean
            Get
                Return CType(Me("DocStyle_PreviewMode"),Boolean)
            End Get
            Set
                Me("DocStyle_PreviewMode") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("70")>  _
        Public Property DocStyle_ConfidenceThreshold() As Integer
            Get
                Return CType(Me("DocStyle_ConfidenceThreshold"),Integer)
            End Get
            Set
                Me("DocStyle_ConfidenceThreshold") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DocStyle_UseConfidenceThreshold() As Boolean
            Get
                Return CType(Me("DocStyle_UseConfidenceThreshold"),Boolean)
            End Get
            Set
                Me("DocStyle_UseConfidenceThreshold") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DocStyle_ProcessTables() As Boolean
            Get
                Return CType(Me("DocStyle_ProcessTables"),Boolean)
            End Get
            Set
                Me("DocStyle_ProcessTables") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property DocStyle_ParagraphsPerCall() As Integer
            Get
                Return CType(Me("DocStyle_ParagraphsPerCall"),Integer)
            End Get
            Set
                Me("DocStyle_ParagraphsPerCall") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property DocStyle_FastModeStylesOnly() As Boolean
            Get
                Return CType(Me("DocStyle_FastModeStylesOnly"),Boolean)
            End Get
            Set
                Me("DocStyle_FastModeStylesOnly") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DocStyle_ShowReport() As Boolean
            Get
                Return CType(Me("DocStyle_ShowReport"),Boolean)
            End Get
            Set
                Me("DocStyle_ShowReport") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property DocStyle_DocumentContext() As String
            Get
                Return CType(Me("DocStyle_DocumentContext"),String)
            End Get
            Set
                Me("DocStyle_DocumentContext") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DocStyle_UseSecondaryModel() As Boolean
            Get
                Return CType(Me("DocStyle_UseSecondaryModel"),Boolean)
            End Get
            Set
                Me("DocStyle_UseSecondaryModel") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
        Public Property DocStyle_ListNumberingReset() As Integer
            Get
                Return CType(Me("DocStyle_ListNumberingReset"),Integer)
            End Get
            Set
                Me("DocStyle_ListNumberingReset") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("4")>  _
        Public Property DocStyle_RuleHeadingOutlineLevelMax() As Integer
            Get
                Return CType(Me("DocStyle_RuleHeadingOutlineLevelMax"),Integer)
            End Get
            Set
                Me("DocStyle_RuleHeadingOutlineLevelMax") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property DocStyle_LastStyleTemplateDisplay() As String
            Get
                Return CType(Me("DocStyle_LastStyleTemplateDisplay"),String)
            End Get
            Set
                Me("DocStyle_LastStyleTemplateDisplay") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DocStyle_RestoreInlineFormatting() As Boolean
            Get
                Return CType(Me("DocStyle_RestoreInlineFormatting"),Boolean)
            End Get
            Set
                Me("DocStyle_RestoreInlineFormatting") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property SelectedToolNames() As String
            Get
                Return CType(Me("SelectedToolNames"),String)
            End Get
            Set
                Me("SelectedToolNames") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ChatEnableTooling() As Boolean
            Get
                Return CType(Me("ChatEnableTooling"),Boolean)
            End Get
            Set
                Me("ChatEnableTooling") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DiscussPersistKnowledge() As Boolean
            Get
                Return CType(Me("DiscussPersistKnowledge"),Boolean)
            End Get
            Set
                Me("DiscussPersistKnowledge") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property DiscussSelectedMission() As String
            Get
                Return CType(Me("DiscussSelectedMission"),String)
            End Get
            Set
                Me("DiscussSelectedMission") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property AutoRespondBreakOff() As String
            Get
                Return CType(Me("AutoRespondBreakOff"),String)
            End Get
            Set
                Me("AutoRespondBreakOff") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("5")>  _
        Public Property AutoRespondMaxRounds() As Integer
            Get
                Return CType(Me("AutoRespondMaxRounds"),Integer)
            End Get
            Set
                Me("AutoRespondMaxRounds") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property AutoRespondMission() As String
            Get
                Return CType(Me("AutoRespondMission"),String)
            End Get
            Set
                Me("AutoRespondMission") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property AutoRespondPersona() As String
            Get
                Return CType(Me("AutoRespondPersona"),String)
            End Get
            Set
                Me("AutoRespondPersona") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property SortOutMainMission() As String
            Get
                Return CType(Me("SortOutMainMission"),String)
            End Get
            Set
                Me("SortOutMainMission") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property SortOutResponderMission() As String
            Get
                Return CType(Me("SortOutResponderMission"),String)
            End Get
            Set
                Me("SortOutResponderMission") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property SortOutMaxRounds() As Integer
            Get
                Return CType(Me("SortOutMaxRounds"),Integer)
            End Get
            Set
                Me("SortOutMaxRounds") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property SortOutMainMissionManual() As String
            Get
                Return CType(Me("SortOutMainMissionManual"),String)
            End Get
            Set
                Me("SortOutMainMissionManual") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property SortOutResponderMissionManual() As String
            Get
                Return CType(Me("SortOutResponderMissionManual"),String)
            End Get
            Set
                Me("SortOutResponderMissionManual") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DiscussEnableTooling() As Boolean
            Get
                Return CType(Me("DiscussEnableTooling"),Boolean)
            End Get
            Set
                Me("DiscussEnableTooling") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DocStyle_RemoveEmptyLines() As Boolean
            Get
                Return CType(Me("DocStyle_RemoveEmptyLines"),Boolean)
            End Get
            Set
                Me("DocStyle_RemoveEmptyLines") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ChatAlternateModelName() As String
            Get
                Return CType(Me("ChatAlternateModelName"),String)
            End Get
            Set
                Me("ChatAlternateModelName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property TableComplete_LastInstructions() As String
            Get
                Return CType(Me("TableComplete_LastInstructions"),String)
            End Get
            Set
                Me("TableComplete_LastInstructions") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property MR_CrossClause() As Boolean
            Get
                Return CType(Me("MR_CrossClause"),Boolean)
            End Get
            Set
                Me("MR_CrossClause") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property MR_Bubbles() As Boolean
            Get
                Return CType(Me("MR_Bubbles"),Boolean)
            End Get
            Set
                Me("MR_Bubbles") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property MR_MarkdownBubbles() As Boolean
            Get
                Return CType(Me("MR_MarkdownBubbles"),Boolean)
            End Get
            Set
                Me("MR_MarkdownBubbles") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property MR_Truncation() As Boolean
            Get
                Return CType(Me("MR_Truncation"),Boolean)
            End Get
            Set
                Me("MR_Truncation") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property MR_MaxChars() As Integer
            Get
                Return CType(Me("MR_MaxChars"),Integer)
            End Get
            Set
                Me("MR_MaxChars") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property MR_UseSecondModel() As Boolean
            Get
                Return CType(Me("MR_UseSecondModel"),Boolean)
            End Get
            Set
                Me("MR_UseSecondModel") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MR_OtherInstructions() As String
            Get
                Return CType(Me("MR_OtherInstructions"),String)
            End Get
            Set
                Me("MR_OtherInstructions") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property MR_HasSaved() As Boolean
            Get
                Return CType(Me("MR_HasSaved"),Boolean)
            End Get
            Set
                Me("MR_HasSaved") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MR_Language() As String
            Get
                Return CType(Me("MR_Language"),String)
            End Get
            Set
                Me("MR_Language") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Stamp_ImagePath() As String
            Get
                Return CType(Me("Stamp_ImagePath"),String)
            End Get
            Set
                Me("Stamp_ImagePath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property Stamp_TopOffset() As Double
            Get
                Return CType(Me("Stamp_TopOffset"),Double)
            End Get
            Set
                Me("Stamp_TopOffset") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property Stamp_RightOffset() As Double
            Get
                Return CType(Me("Stamp_RightOffset"),Double)
            End Get
            Set
                Me("Stamp_RightOffset") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property Stamp_Width() As Double
            Get
                Return CType(Me("Stamp_Width"),Double)
            End Get
            Set
                Me("Stamp_Width") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property Stamp_TextTopOffset() As Double
            Get
                Return CType(Me("Stamp_TextTopOffset"),Double)
            End Get
            Set
                Me("Stamp_TextTopOffset") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property Stamp_TextRightOffset() As Double
            Get
                Return CType(Me("Stamp_TextRightOffset"),Double)
            End Get
            Set
                Me("Stamp_TextRightOffset") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property Stamp_TextSize() As Double
            Get
                Return CType(Me("Stamp_TextSize"),Double)
            End Get
            Set
                Me("Stamp_TextSize") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Stamp_Prefix() As String
            Get
                Return CType(Me("Stamp_Prefix"),String)
            End Get
            Set
                Me("Stamp_Prefix") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Stamp_Suffix() As String
            Get
                Return CType(Me("Stamp_Suffix"),String)
            End Get
            Set
                Me("Stamp_Suffix") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Stamp_UseLLM() As Boolean
            Get
                Return CType(Me("Stamp_UseLLM"),Boolean)
            End Get
            Set
                Me("Stamp_UseLLM") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Stamp_OutputSubdir() As String
            Get
                Return CType(Me("Stamp_OutputSubdir"),String)
            End Get
            Set
                Me("Stamp_OutputSubdir") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Stamp_OutputExtension() As String
            Get
                Return CType(Me("Stamp_OutputExtension"),String)
            End Get
            Set
                Me("Stamp_OutputExtension") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Stamp_Regex() As String
            Get
                Return CType(Me("Stamp_Regex"),String)
            End Get
            Set
                Me("Stamp_Regex") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property LastImageGenPrompt() As String
            Get
                Return CType(Me("LastImageGenPrompt"),String)
            End Get
            Set
                Me("LastImageGenPrompt") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Tabular_ManualInstruction() As String
            Get
                Return CType(Me("Tabular_ManualInstruction"),String)
            End Get
            Set
                Me("Tabular_ManualInstruction") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Tabular_ManualSchema() As String
            Get
                Return CType(Me("Tabular_ManualSchema"),String)
            End Get
            Set
                Me("Tabular_ManualSchema") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Tabular_DateColumns() As String
            Get
                Return CType(Me("Tabular_DateColumns"),String)
            End Get
            Set
                Me("Tabular_DateColumns") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Tabular_SortColumn() As String
            Get
                Return CType(Me("Tabular_SortColumn"),String)
            End Get
            Set
                Me("Tabular_SortColumn") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ASC")>  _
        Public Property Tabular_SortDirection() As String
            Get
                Return CType(Me("Tabular_SortDirection"),String)
            End Get
            Set
                Me("Tabular_SortDirection") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Tabular_DoOcr() As Boolean
            Get
                Return CType(Me("Tabular_DoOcr"),Boolean)
            End Get
            Set
                Me("Tabular_DoOcr") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Tabular_DateClampFrom() As String
            Get
                Return CType(Me("Tabular_DateClampFrom"),String)
            End Get
            Set
                Me("Tabular_DateClampFrom") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Tabular_DateClampTo() As String
            Get
                Return CType(Me("Tabular_DateClampTo"),String)
            End Get
            Set
                Me("Tabular_DateClampTo") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Tabular_OutputLanguage() As String
            Get
                Return CType(Me("Tabular_OutputLanguage"),String)
            End Get
            Set
                Me("Tabular_OutputLanguage") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Tabular_DateOutputFormat() As String
            Get
                Return CType(Me("Tabular_DateOutputFormat"),String)
            End Get
            Set
                Me("Tabular_DateOutputFormat") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Tabular_MergeEnable() As Boolean
            Get
                Return CType(Me("Tabular_MergeEnable"),Boolean)
            End Get
            Set
                Me("Tabular_MergeEnable") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Tabular_MergeDateColumn() As String
            Get
                Return CType(Me("Tabular_MergeDateColumn"),String)
            End Get
            Set
                Me("Tabular_MergeDateColumn") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Tabular_MergeInstruction() As String
            Get
                Return CType(Me("Tabular_MergeInstruction"),String)
            End Get
            Set
                Me("Tabular_MergeInstruction") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.Red_Ink_for_Word.My.MySettings
            Get
                Return Global.Red_Ink_for_Word.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
