'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2025-01-01")>  _
        Public Property LastUpdateCheckWord() As Date
            Get
                Return CType(Me("LastUpdateCheckWord"),Date)
            End Get
            Set
                Me("LastUpdateCheckWord") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2000-01-01")>  _
        Public Property LastUpdateCheckExcel() As Date
            Get
                Return CType(Me("LastUpdateCheckExcel"),Date)
            End Get
            Set
                Me("LastUpdateCheckExcel") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2000-01-01")>  _
        Public Property LastUpdateCheckOutlook() As Date
            Get
                Return CType(Me("LastUpdateCheckOutlook"),Date)
            End Get
            Set
                Me("LastUpdateCheckOutlook") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property LastAnonPrompt() As String
            Get
                Return CType(Me("LastAnonPrompt"),String)
            End Get
            Set
                Me("LastAnonPrompt") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property PaneWidth() As Integer
            Get
                Return CType(Me("PaneWidth"),Integer)
            End Get
            Set
                Me("PaneWidth") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property PromptLog() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("PromptLog"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("PromptLog") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property UpdateRetryDateWord() As Date
            Get
                Return CType(Me("UpdateRetryDateWord"),Date)
            End Get
            Set
                Me("UpdateRetryDateWord") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property UpdateRetryCountWord() As Integer
            Get
                Return CType(Me("UpdateRetryCountWord"),Integer)
            End Get
            Set
                Me("UpdateRetryCountWord") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property UpdateRetryPromptShownWord() As Boolean
            Get
                Return CType(Me("UpdateRetryPromptShownWord"),Boolean)
            End Get
            Set
                Me("UpdateRetryPromptShownWord") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property UpdateRetryDateExcel() As Date
            Get
                Return CType(Me("UpdateRetryDateExcel"),Date)
            End Get
            Set
                Me("UpdateRetryDateExcel") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property UpdateRetryCountExcel() As Integer
            Get
                Return CType(Me("UpdateRetryCountExcel"),Integer)
            End Get
            Set
                Me("UpdateRetryCountExcel") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property UpdateRetryPromptShownExcel() As Boolean
            Get
                Return CType(Me("UpdateRetryPromptShownExcel"),Boolean)
            End Get
            Set
                Me("UpdateRetryPromptShownExcel") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property UpdateRetryDateOutlook() As Date
            Get
                Return CType(Me("UpdateRetryDateOutlook"),Date)
            End Get
            Set
                Me("UpdateRetryDateOutlook") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property UpdateRetryCountOutlook() As Integer
            Get
                Return CType(Me("UpdateRetryCountOutlook"),Integer)
            End Get
            Set
                Me("UpdateRetryCountOutlook") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property UpdateRetryPromptShownOutlook() As Boolean
            Get
                Return CType(Me("UpdateRetryPromptShownOutlook"),Boolean)
            End Get
            Set
                Me("UpdateRetryPromptShownOutlook") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property LastHelpMeChat() As String
            Get
                Return CType(Me("LastHelpMeChat"),String)
            End Get
            Set
                Me("LastHelpMeChat") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property LastHelpMeChatHtml() As String
            Get
                Return CType(Me("LastHelpMeChatHtml"),String)
            End Get
            Set
                Me("LastHelpMeChatHtml") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0, 0")>  _
        Public Property HelpMeFormLocation() As Global.System.Drawing.Point
            Get
                Return CType(Me("HelpMeFormLocation"),Global.System.Drawing.Point)
            End Get
            Set
                Me("HelpMeFormLocation") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0, 0")>  _
        Public Property HelpMeFormSize() As Global.System.Drawing.Size
            Get
                Return CType(Me("HelpMeFormSize"),Global.System.Drawing.Size)
            End Get
            Set
                Me("HelpMeFormSize") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property HelpMeNoTopMost() As Boolean
            Get
                Return CType(Me("HelpMeNoTopMost"),Boolean)
            End Get
            Set
                Me("HelpMeNoTopMost") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property DefaultPrefix() As String
            Get
                Return CType(Me("DefaultPrefix"),String)
            End Get
            Set
                Me("DefaultPrefix") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ReplaceText2Override() As String
            Get
                Return CType(Me("ReplaceText2Override"),String)
            End Get
            Set
                Me("ReplaceText2Override") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MarkupMethodWordOverride() As String
            Get
                Return CType(Me("MarkupMethodWordOverride"),String)
            End Get
            Set
                Me("MarkupMethodWordOverride") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MarkupMethodOutlookOverride() As String
            Get
                Return CType(Me("MarkupMethodOutlookOverride"),String)
            End Get
            Set
                Me("MarkupMethodOutlookOverride") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property HelpMeIncludeConfig() As Boolean
            Get
                Return CType(Me("HelpMeIncludeConfig"),Boolean)
            End Get
            Set
                Me("HelpMeIncludeConfig") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property LicensedTill() As Date
            Get
                Return CType(Me("LicensedTill"),Date)
            End Get
            Set
                Me("LicensedTill") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property LicenseStatus() As String
            Get
                Return CType(Me("LicenseStatus"),String)
            End Get
            Set
                Me("LicenseStatus") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property LicenseUsers() As Integer
            Get
                Return CType(Me("LicenseUsers"),Integer)
            End Get
            Set
                Me("LicenseUsers") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property LastBetaWarningDate() As Date
            Get
                Return CType(Me("LastBetaWarningDate"),Date)
            End Get
            Set
                Me("LastBetaWarningDate") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property BetaWarningStartCount() As Integer
            Get
                Return CType(Me("BetaWarningStartCount"),Integer)
            End Get
            Set
                Me("BetaWarningStartCount") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property GracePeriodWarningStartcount() As Integer
            Get
                Return CType(Me("GracePeriodWarningStartcount"),Integer)
            End Get
            Set
                Me("GracePeriodWarningStartcount") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property LicenseWarningStartCount() As Integer
            Get
                Return CType(Me("LicenseWarningStartCount"),Integer)
            End Get
            Set
                Me("LicenseWarningStartCount") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property IgnoredUpdates_RedInk() As String
            Get
                Return CType(Me("IgnoredUpdates_RedInk"),String)
            End Get
            Set
                Me("IgnoredUpdates_RedInk") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property IgnoredUpdates_Custom() As String
            Get
                Return CType(Me("IgnoredUpdates_Custom"),String)
            End Get
            Set
                Me("IgnoredUpdates_Custom") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property QuickTranslateLanguage() As String
            Get
                Return CType(Me("QuickTranslateLanguage"),String)
            End Get
            Set
                Me("QuickTranslateLanguage") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property QuickTranslateX() As Integer
            Get
                Return CType(Me("QuickTranslateX"),Integer)
            End Get
            Set
                Me("QuickTranslateX") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property QuickTranslateY() As Integer
            Get
                Return CType(Me("QuickTranslateY"),Integer)
            End Get
            Set
                Me("QuickTranslateY") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property QuickTranslateWidth() As Integer
            Get
                Return CType(Me("QuickTranslateWidth"),Integer)
            End Get
            Set
                Me("QuickTranslateWidth") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property QuickTranslateHeight() As Integer
            Get
                Return CType(Me("QuickTranslateHeight"),Integer)
            End Get
            Set
                Me("QuickTranslateHeight") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property License_Type() As String
            Get
                Return CType(Me("License_Type"),String)
            End Get
            Set
                Me("License_Type") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property License_ProductID() As String
            Get
                Return CType(Me("License_ProductID"),String)
            End Get
            Set
                Me("License_ProductID") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property License_Key() As String
            Get
                Return CType(Me("License_Key"),String)
            End Get
            Set
                Me("License_Key") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property License_UserID() As String
            Get
                Return CType(Me("License_UserID"),String)
            End Get
            Set
                Me("License_UserID") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property License_ProductName() As String
            Get
                Return CType(Me("License_ProductName"),String)
            End Get
            Set
                Me("License_ProductName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property License_ActivatedOn() As Date
            Get
                Return CType(Me("License_ActivatedOn"),Date)
            End Get
            Set
                Me("License_ActivatedOn") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property License_ValidUntil() As Date
            Get
                Return CType(Me("License_ValidUntil"),Date)
            End Get
            Set
                Me("License_ValidUntil") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property License_LastCheck() As Date
            Get
                Return CType(Me("License_LastCheck"),Date)
            End Get
            Set
                Me("License_LastCheck") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property License_PrivateConfirmedOn() As Date
            Get
                Return CType(Me("License_PrivateConfirmedOn"),Date)
            End Get
            Set
                Me("License_PrivateConfirmedOn") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property License_PrivateVersion() As String
            Get
                Return CType(Me("License_PrivateVersion"),String)
            End Get
            Set
                Me("License_PrivateVersion") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property License_PrivateDismissCount() As Integer
            Get
                Return CType(Me("License_PrivateDismissCount"),Integer)
            End Get
            Set
                Me("License_PrivateDismissCount") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property License_OfflineGraceStart() As Date
            Get
                Return CType(Me("License_OfflineGraceStart"),Date)
            End Get
            Set
                Me("License_OfflineGraceStart") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property License_GracePeriodStart() As Date
            Get
                Return CType(Me("License_GracePeriodStart"),Date)
            End Get
            Set
                Me("License_GracePeriodStart") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property License_State() As String
            Get
                Return CType(Me("License_State"),String)
            End Get
            Set
                Me("License_State") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property License_AutoActivationWarningShown() As Boolean
            Get
                Return CType(Me("License_AutoActivationWarningShown"),Boolean)
            End Get
            Set
                Me("License_AutoActivationWarningShown") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property License_LastMigrationPrompt() As Date
            Get
                Return CType(Me("License_LastMigrationPrompt"),Date)
            End Get
            Set
                Me("License_LastMigrationPrompt") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property License_StartupCount() As Integer
            Get
                Return CType(Me("License_StartupCount"),Integer)
            End Get
            Set
                Me("License_StartupCount") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property License_ApiConfirmed() As Boolean
            Get
                Return CType(Me("License_ApiConfirmed"),Boolean)
            End Get
            Set
                Me("License_ApiConfirmed") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property License_LegacyMigrationStarted() As Date
            Get
                Return CType(Me("License_LegacyMigrationStarted"),Date)
            End Get
            Set
                Me("License_LegacyMigrationStarted") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0, 0, 0, 0")>  _
        Public Property RTFMessageBoxBounds() As Global.System.Drawing.Rectangle
            Get
                Return CType(Me("RTFMessageBoxBounds"),Global.System.Drawing.Rectangle)
            End Get
            Set
                Me("RTFMessageBoxBounds") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.SharedLibrary.My.MySettings
            Get
                Return Global.SharedLibrary.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
